// @generated by scripts/generateRustConstants.ts — DO NOT EDIT
//
// Regenerate with: pnpm generate:rust-constants

/// CSS properties which accept numbers but are not in units of "px".
/// Sorted alphabetically for binary_search.
pub const UNITLESS_NUMBERS: &[&str] = &[
    "MozAnimationIterationCount",
    "MozBoxFlex",
    "MozBoxFlexGroup",
    "MozLineClamp",
    "WebKitBoxFlexGroup",
    "WebkitAnimationIterationCount",
    "WebkitBoxFlex",
    "WebkitBoxOrdinalGroup",
    "WebkitColumnCount",
    "WebkitColumns",
    "WebkitFlex",
    "WebkitFlexGrow",
    "WebkitFlexPositive",
    "WebkitFlexShrink",
    "WebkitLineClamp",
    "animationIterationCount",
    "aspectRatio",
    "borderImageOutset",
    "borderImageSlice",
    "borderImageWidth",
    "boxFlex",
    "boxFlexGroup",
    "boxOrdinalGroup",
    "columnCount",
    "columns",
    "fillOpacity",
    "flex",
    "flexGrow",
    "flexNegative",
    "flexOrder",
    "flexPositive",
    "flexShrink",
    "floodOpacity",
    "fontWeight",
    "gridArea",
    "gridColumn",
    "gridColumnEnd",
    "gridColumnSpan",
    "gridColumnStart",
    "gridRow",
    "gridRowEnd",
    "gridRowSpan",
    "gridRowStart",
    "lineClamp",
    "lineHeight",
    "msAnimationIterationCount",
    "msFlex",
    "msFlexGrow",
    "msFlexNegative",
    "msFlexOrder",
    "msFlexPositive",
    "msFlexShrink",
    "msGridColumn",
    "msGridColumnSpan",
    "msGridRow",
    "msGridRowSpan",
    "msZoom",
    "opacity",
    "order",
    "orphans",
    "scale",
    "stopOpacity",
    "strokeDasharray",
    "strokeDashoffset",
    "strokeMiterlimit",
    "strokeOpacity",
    "strokeWidth",
    "tabSize",
    "widows",
    "zIndex",
    "zoom",
];

/// Pseudoelements recognized by jsxstyle as prop name prefixes.
pub const PSEUDOELEMENTS: &[&str] = &["after", "before", "placeholder", "selection"];

/// Pseudoclasses recognized by jsxstyle as prop name prefixes.
pub const PSEUDOCLASSES: &[&str] = &[
    "active", "checked", "disabled", "empty", "enabled", "focus", "hover", "invalid", "link",
    "required", "target", "valid",
];

/// CSS property prefixes that trigger double specificity (+1).
pub const DOUBLE_SPECIFICITY_PREFIXES: &[&str] = &[
    "animation",
    "background",
    "flex",
    "font",
    "margin",
    "padding",
];

/// Props consumed by the extractor itself, not passed through to the output element.
pub const SKIPPED_PROPS: &[&str] = &["component", "mediaQueries", "props"];

/// HTML attributes that pass through to the DOM element untouched at runtime.
pub const COMMON_COMPONENT_PROPS: &[&str] = &[
    "alt",
    "checked",
    "children",
    "class",
    "className",
    "disabled",
    "href",
    "id",
    "name",
    "placeholder",
    "slot",
    "src",
    "style",
    "title",
    "type",
    "value",
];

/// Valid jsxstyle source packages.
pub const JSXSTYLE_SOURCES: &[&str] = &["@jsxstyle/react", "@jsxstyle/preact", "@jsxstyle/solid"];

/// Valid jsxstyle component names (derived from componentStyles keys).
pub const VALID_COMPONENTS: &[&str] = &[
    "Block",
    "Box",
    "Col",
    "Grid",
    "Inline",
    "InlineBlock",
    "InlineCol",
    "InlineRow",
    "Row",
];

/// Known non-component imports from jsxstyle packages.
pub const KNOWN_NON_COMPONENT_IMPORTS: &[&str] = &["useMatchMedia", "makeCustomProperties", "css"];

/// Shorthand prop expansions.
/// Returns None if the prop name is not a shorthand.
/// Returns Some(vec of expanded prop names) if it is.
pub fn expand_shorthand(prop_name: &str) -> Option<&'static [&'static str]> {
    match prop_name {
        "marginH" => Some(&["marginLeft", "marginRight"]),
        "marginV" => Some(&["marginTop", "marginBottom"]),
        "paddingH" => Some(&["paddingLeft", "paddingRight"]),
        "paddingV" => Some(&["paddingTop", "paddingBottom"]),
        _ => None,
    }
}

/// Get the default style properties for a jsxstyle component.
///
/// Returns `None` for `Box` (which has no defaults) and for unknown names.
pub fn get_component_defaults(name: &str) -> Option<&'static [(&'static str, &'static str)]> {
    match name {
        "Block" => Some(&[("display", "block")]),
        "Box" => None,
        "Col" => Some(&[("display", "flex"), ("flexDirection", "column")]),
        "Grid" => Some(&[("display", "grid")]),
        "Inline" => Some(&[("display", "inline")]),
        "InlineBlock" => Some(&[("display", "inline-block")]),
        "InlineCol" => Some(&[("display", "inline-flex"), ("flexDirection", "column")]),
        "InlineRow" => Some(&[
            ("display", "inline-flex"),
            ("flexDirection", "row"),
            ("alignItems", "center"),
        ]),
        "Row" => Some(&[
            ("display", "flex"),
            ("flexDirection", "row"),
            ("alignItems", "center"),
        ]),
        _ => None,
    }
}
