name: Bug report
description: File a bug report
title: "Bug: "
labels: [bug]
assignees:
  - meyer

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Feel free to provide as much information as you can so that we can find the bug and fix it.

        If you’re not 100% sure what’s causing the bug, you can paste error messages and/or a stack trace in the “Additional context” text box and we’ll start from there.

  - type: textarea
    id: bug-description
    attributes:
      label: What’s happening?
      placeholder: "example: When I set the `color` prop to `red`, the text turns blue."
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What should be happening instead?
      placeholder: "example: The text should be red."
    validations:
      required: true

  - type: input
    id: repro-link
    attributes:
      label: Link to repro
      description: If it’s a weird enough bug, a minimal reproduction would be super helpful. In most cases a repro isn’t necessary though.
      placeholder: "https://github.com/your-github-username/jsxstyle-bug-repro"
    validations:
      required: false

  - type: dropdown
    id: buggy-package
    attributes:
      label: Which package is causing this issue?
      options:
        - jsxstyle
        - jsxstyle-webpack-plugin
        - gatsby-plugin-jsxstyle
        - jsxstyle-utils
    validations:
      required: true

  - type: dropdown
    id: browsers
    validations:
      required: false
    attributes:
      label: Which browser(s) are exhibiting this issue?
      description: You can skip this question if the issue is being caused by jsxstyle-webpack-plugin.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Safari on iOS
        - Chrome on Android
        - A browser not listed here (please provide more information below)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything you can provide that would make debugging this issue a bit easier would be super helpful!
    validations:
      required: false
