import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  commonComponentProps,
  componentStyles,
  doubleSpecificityPrefixes,
  jsxstyleSources,
  nonComponentImports,
  pseudoClasses,
  pseudoElements,
  shorthandExpansions,
  skippedProps,
  unitlessNumbers,
} from '@jsxstyle/core';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(
  __dirname,
  '../crates/jsxstyle-swc-core/src/generated_constants.rs'
);

function toStringArray(
  input: ReadonlySet<string> | Record<string, unknown> | readonly string[]
): string[] {
  if (input instanceof Set) return [...input];
  if (Array.isArray(input)) return input;
  return Object.keys(input);
}

function rustStringArray(
  name: string,
  items: ReadonlySet<string> | Record<string, unknown> | readonly string[]
): string {
  const arr = toStringArray(items);
  const inner = arr.map((s) => `    "${s}",`).join('\n');
  return `pub const ${name}: &[&str] = &[\n${inner}\n];`;
}

function generateExpandShorthand(
  expansions: readonly { shorthand: string; expanded: readonly string[] }[]
): string {
  const arms = expansions
    .map((e) => {
      const expanded = e.expanded.map((s) => `"${s}"`).join(', ');
      return `        "${e.shorthand}" => Some(&[${expanded}]),`;
    })
    .join('\n');

  return `pub fn expand_shorthand(prop_name: &str) -> Option<&'static [&'static str]> {
    match prop_name {
${arms}
        _ => None,
    }
}`;
}

function generateGetComponentDefaults(
  styles: Record<string, Record<string, string> | null>
): string {
  const arms = Object.entries(styles)
    .map(([name, props]) => {
      if (props === null) {
        return `        "${name}" => None,`;
      }
      const tuples = Object.entries(props)
        .map(([k, v]) => `("${k}", "${v}")`)
        .join(', ');
      return `        "${name}" => Some(&[${tuples}]),`;
    })
    .join('\n');

  return `pub fn get_component_defaults(name: &str) -> Option<&'static [(&'static str, &'static str)]> {
    match name {
${arms}
        _ => None,
    }
}`;
}

// Sort alphabetically for binary_search in Rust
const sortedUnitlessNumbers = toStringArray(unitlessNumbers).sort();

// Component names derived from componentStyles keys
const validComponents = Object.keys(componentStyles);

const output = `// @generated by scripts/generateRustConstants.ts — DO NOT EDIT
//
// Regenerate with: pnpm generate:rust-constants

/// CSS properties which accept numbers but are not in units of "px".
/// Sorted alphabetically for binary_search.
${rustStringArray('UNITLESS_NUMBERS', sortedUnitlessNumbers)}

/// Pseudoelements recognized by jsxstyle as prop name prefixes.
${rustStringArray('PSEUDOELEMENTS', pseudoElements)}

/// Pseudoclasses recognized by jsxstyle as prop name prefixes.
${rustStringArray('PSEUDOCLASSES', pseudoClasses)}

/// CSS property prefixes that trigger double specificity (+1).
${rustStringArray('DOUBLE_SPECIFICITY_PREFIXES', doubleSpecificityPrefixes)}

/// Props consumed by the extractor itself, not passed through to the output element.
${rustStringArray('SKIPPED_PROPS', skippedProps)}

/// HTML attributes that pass through to the DOM element untouched at runtime.
${rustStringArray('COMMON_COMPONENT_PROPS', commonComponentProps)}

/// Valid jsxstyle source packages.
${rustStringArray('JSXSTYLE_SOURCES', jsxstyleSources)}

/// Valid jsxstyle component names (derived from componentStyles keys).
${rustStringArray('VALID_COMPONENTS', validComponents)}

/// Known non-component imports from jsxstyle packages.
${rustStringArray('KNOWN_NON_COMPONENT_IMPORTS', nonComponentImports)}

/// Shorthand prop expansions.
/// Returns None if the prop name is not a shorthand.
/// Returns Some(vec of expanded prop names) if it is.
${generateExpandShorthand(shorthandExpansions)}

/// Get the default style properties for a jsxstyle component.
///
/// Returns \`None\` for \`Box\` (which has no defaults) and for unknown names.
${generateGetComponentDefaults(componentStyles as Record<string, Record<string, string> | null>)}
`;

fs.writeFileSync(outputPath, output);

// Format the generated file so it matches CI's `cargo fmt --check`. Run from
// crates/ so the toolchain pinned in crates/rust-toolchain.toml is used.
const cratesDir = path.resolve(__dirname, '..', 'crates');
execFileSync('cargo', ['fmt', '--package', 'jsxstyle-swc-core'], {
  cwd: cratesDir,
  stdio: 'inherit',
});

console.log(`Generated ${path.relative(process.cwd(), outputPath)}`);
