/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extract non-jsxstyle import specifiers from source code using SWC's parser.
 *
 * Parses the source as TypeScript/TSX and walks the AST for ImportDecl nodes.
 * Returns specifier strings for all imports that are not jsxstyle packages.
 * Includes relative imports (`./foo`), aliased paths (`@/foo`), and bare
 * specifiers (`lodash`) — the bundler resolver handles path resolution.
 */
export declare function extractImportSpecifiers(source: string): Array<string>

/**
 * Transform jsxstyle components in source code, extracting static styles to CSS.
 *
 * Parses the source with SWC (TSX syntax), applies the jsxstyle transform visitor,
 * codegens the transformed AST, and returns code, CSS, source map, cache, and diagnostics.
 *
 * # Arguments
 * * `source` - The source code to transform
 * * `filename` - The filename for error reporting and source maps
 * * `options` - Transform options with serialized configuration (no JS callbacks)
 *
 * # Returns
 * A `TransformOutput` with `code`, `css`, `map`, `cacheObject`, `errors`, `warnings`, `staticExports`
 */
export declare function transform(source: string, filename: string, options: TransformOptions): TransformOutput

/**
 * Options for the jsxstyle transform.
 *
 * All options are serialized data (no JS Function callbacks). Class name
 * generation happens entirely in Rust.
 */
export interface TransformOptions {
  /** Class name strategy: "counter" for sequential, "hash" for content-based. */
  classNameStrategy: string
  /** Prefix for generated class names (e.g., "_x"). */
  classNamePrefix: string
  /** Enable debug class names in dev mode. */
  debugClassNames?: boolean
  /**
   * Pre-populated cache object for persistent class name mapping.
   * Maps style key -> class name. Returned in the output for persistence.
   */
  cacheObject?: Record<string, string>
  /**
   * Enables noRuntime mode where unextractable style props trigger diagnostics.
   * Valid values: "warn" or "error".
   */
  noRuntime?: string
  /**
   * Static exports from dependency modules, keyed by import specifier.
   * Specifier is the raw string from the import declaration (e.g., "./tokens").
   * Each module maps export name -> JSON-serialized static value.
   */
  externalBindings?: Record<string, Record<string, any>>
}

/** Result of transforming jsxstyle source code. */
export interface TransformOutput {
  /** The transformed JavaScript source code. */
  code: string
  /** The extracted CSS rules. */
  css: string
  /** JSON-serialized source map, if available. */
  map?: string
  /**
   * Cache object containing all style key -> class name mappings.
   * Pass back into the next transform call for consistent class names.
   */
  cacheObject: Record<string, string>
  /** Error messages collected during the transform (noRuntime "error" mode). */
  errors: Array<string>
  /** Warning messages collected during the transform (noRuntime "warn" mode). */
  warnings: Array<string>
  /**
   * Static exports detected in this module.
   * Maps export name -> JSON-serialized static value.
   */
  staticExports: Record<string, any>
}
