name: Publish canary release

on:
  push:
    branches:
      - main

jobs:
  canary:
    name: Create and publish a new release
    if: ${{ !startsWith(github.event.head_commit.message, 'Bump versions') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm build
      - run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish canary release
        run: |
          pnpm version:canary
          pnpm release:canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
